### ISSUE TITLE
Looker dashboard shows old season data?

### ISSUE THREAD

**Issue by thecloudtechnologist** [dumaaan/fpl_analytics#1]
https://github.com/dumaaan/fpl_analytics/blob/960d54f83d165791fd17b67242c2639f4eb48020/fetch_data.py#L18

I think this needs to be updated to reflect the new [season](https://github.com/vaastav/Fantasy-Premier-League/tree/master/data/2024-25).

**Comment by dumaaan** [comment]
Thanks for the heads-up! `fetch_data.py` actually was a one-time parsing script for downloading past seasons historical data. I am currently working on upgrading reworking the script data entirely, and this is why the Looker dashboard is not reflecting the new season. 

But in case you need the Looker dashboard, I will do a quickfix and update that!
